### ISSUE TITLE
TextInput

### ISSUE THREAD

**Issue by testllg** [Megabyteceer/thing-editor#38]
Hi:
    When I used TextInput in iOS Safari ,  The input keyboard  blocked the TextInput interface.  Any suggestions?
     Android is worked fine.

**Comment by Megabyteceer** [comment]
Its only way to avoid overlapping - place text inputs at the top of screen. I use popup for enter text values. You can see  example-project. One of the buttons in main scene has "classes.TextInput.prompt..." handler. It is shows text input dialogue.
We have used text inputs in few projects, but discarded it, because text input in game is not very good expirience.
Apple makes many things to make web games development harder.

**Comment by testllg** [comment]
In text-input.js, htmlInput opacity=0,  When I set opacity=1, the htmlInput is showed  at top-left ,  moved  htmlInput to bottom, keyboard can push interface to top.  Can I sync  htmlInput and textinput position?

**Comment by Megabyteceer** [comment]
I made commit to Text-input-ios-fix branch. Can you please check if it fixes your problem, and i will merge it to master.
https://github.com/Megabyteceer/thing-editor/compare/master...Text-input-ios-fix

**Comment by testllg** [comment]
I test this branch In my iPhone. 
1 Without input, keyboard blocked TextInput, When I input some thing, interface pushed to 
suitable location.
2  I edit htmlInput opacity != 0,  It worked fine even without input. But htmlInput is showed, I move left   outside the screen to hide it.
